### PR TITLE
[service_discovery] adding jmx check for service discovery

### LINKED ISSUE #287: Service Discovery JMX options
The option to enable JMX service discovery in `datadog.conf` is missing. Make sure we address this in the next release.

### PR DESCRIPTION
**Pull request by alvin-huang**
Closes #287

### CODE REVIEW

**Comment by truthbk** [comment]
Thanks @alvin-huang 👍  This was surely due, and makes plenty of sense given the new feature. We're going to have to pin `nokogiri` to a lower version, I think. Mainly because we have to maintain compatibility with older puppets.

Thanks!

**Comment by truthbk** [comment]
@alvin-huang could you be so kind as to rebase this to the latest master? That should fix up the CI issues we encountered in the past with the unwanted `nokogiri` upgrade (it's not pinned).

**Comment by alvin-huang** [comment]
@truthbk not a problem-- rebased and ready to go!

**Comment by truthbk** [comment]
Thanks for the rebase! Merging in this one!

**Pull request merged**
