### PR TITLE
Add content_match argument in http_checks integration

### PR DESCRIPTION
**Pull request by cristianjuve**

### CODE REVIEW

**Comment by truthbk** [comment]
@cristianjuve Thank you so much for the contribution., unfortunately it's missing the spec tests. It would be fantastic if you could add a couple test cases.

**Comment by truthbk** [comment]
awesome! Thanks a lot @cristianjuve

**Comment by truthbk** [comment]
I think you're done, but can you confirm before I merge?

**Comment by cristianjuve** [comment]
Hi @truthbk, you can merge this branch :)
thk

**Comment by truthbk** [comment]
Thanks @cristianjuve :shipit:

**Pull request merged**
