### PR TITLE
Add client configuration info

### PR DESCRIPTION
**Pull request by unixorn**
* Added instructions for setting host tags for nodes
* Documented some other client toggle variables
* Documented which variables control proxy usage by dd-agent

### CODE REVIEW

**Comment by unixorn** [comment]
This PR only changes `README.md`. It looks like travis is having some issues with bundler when it tries to run the checks.

**Comment by irabinovitch** [comment]
@unixorn  Thanks for helping improve our docs.  I'm copying @truthbk  to help take a look at why tests are failing.

**Comment by unixorn** [comment]
@irabinovitch, @truthbk What do I need to do to get this merged?

**Comment by truthbk** [comment]
@unixorn this will be merged into the next major release. We just made a bugfix release, but that was long overdue, so it shouldn't be too long. Could you please rebase to the latest master so we can get CI passing again? Thanks!

**Comment by unixorn** [comment]
@truthbk NP, Done.

**Pull request merged**
