### PR TITLE
[redis] support multiple ports for a single host

### PR DESCRIPTION
**Pull request by fzwart**
I've added support for configuring multiple redis instances for a single host.

### CODE REVIEW

**Comment by truthbk** [comment]
Hi @fzwart I don't think the actual agent redis check supports an array of ports as a config parameter. Do you run a custom redis check?

**Comment by truthbk** [comment]
@fzwart I misread the template, I see what you're doing creating an instance per port. Will need to polish this to avoid breaking any existing configs due to potential backward compatibility issues.

**Comment by fzwart** [comment]
Hi @truthbk,

Sorry for my late response, would be great if you could eventually merge it!

**Comment by truthbk** [comment]
@fzwart I'll be making a small change to make it backward compatible by keeping the port parameter as well and then feeding it to the template. But I'll respect your authorship here. It's a small change and I have to test the manifest anyways, so no worries I can take care of it. Thank you very much, once again.

**Comment by truthbk** [comment]
Included in #176, thanks!

**Pull request closed without merging**
