### PR TITLE
Allow open files limit param

### PR DESCRIPTION
**Pull request by mylivingweb**
Allow users to configure open files limit with hiera or manifests

### CODE REVIEW

**Comment by albertvaka** [comment]
Hi @mylivingweb and thanks for your contribution!

Can you make the option default to "undef", and only set it in `logs_config` if it has been defined? This way, if it's not set, the agent will use its default value, and if the that default ever changes, we won't have to change it also here.

It is definitely a good idea to expose this config param via the puppet module, but I think it's better to avoid duplicating default values in puppet and the agent code.

**Comment by mylivingweb** [comment]
makes sense, i'll work on it

**Comment by albertvaka** [comment]
Can I ask you one more change? Can we call this `logs_open_files_limit` and mention in the documentation that this is only for the logs agent? Could be something like `Set the max open files for the logs agent.`

Otherwise, people might think this affect all datadog agents, while it only affects the logs agent.

**Comment by mylivingweb** [comment]
sure, i can rename it, it is actually breaking in our dev environment anyway so still need a little work

**Comment by mylivingweb** [comment]
tested in our dev environment with the latest commit.
`datadog_agent::logs_open_files_limit: 2000`
or
```
class { "datadog_agent":
    api_key               => "***",
    logs_enabled          => true,
    logs_open_files_limit => 2000,
  }
```

**Comment by mylivingweb** [comment]
any word on merging?

**Comment by albertvaka** [comment]
Looks good to me! Thanks for the patch and sorry for the delay, I was on vacation and I'm just catching up 🌴🙂

**Comment by mylivingweb** [comment]
awesome, thanks

**Pull request merged**
