### PR TITLE
Make a generic define for creating modules

### PR DESCRIPTION
**Pull request by truthbk**
There is one already but only allows one since its a class we can not do
a bunch of integrations and replace the class with this. Also this will
allow you to write ruby, or hiera and put it in the config you need.

Supersedes #141 - it's still all @cwood work. His PR had been sitting there for so long I felt bad asking him to do this for us. This just rebases to the latest master and makes sure the CI passes. 

Thank you @cwood!

### CODE REVIEW

**Comment by cwood** [comment]
@truthbk I have some other stuff that we have been using at bitbucket. This has been essential since we have stopped using any of the class intergrations and just use the heira way of datadog_agent::intergrations -> define intergration and plop out the yaml file. 

If you need any help I can do what I can.

**Comment by truthbk** [comment]
CI is failing on older puppet versions... working on a fix.

**Comment by truthbk** [comment]
So the YAML parser is dumping different yaml when the puppet gem is `< 4.0.0`. Added a patch that fixes the spec tests and takes into account both versions.

@cwood should we merge this? Or there's additional work you were referring to above that you would like to add? Can we merge this and then you can add on top, or would we need to write a PR from scratch. 

Thanks!

**Comment by cwood** [comment]
@truthbk there is some more we have added. I have also redun the way to manage tags and making them resources vs just combining them together. I can submit that as another PR. it is using concat. We have also added a intergrations argumetn and a use_hiera argument to allow a deep merge of datadog intergrations through heira.

**Pull request merged**
