### PR TITLE
Add custom MySQL metrics

### PR DESCRIPTION
**Pull request by yrcjaya**
Manage custom MySQL metrics

### CODE REVIEW

**Comment by truthbk** [comment]
@yrcjaya I know this has been a while ago, I'm sorry this got cut from the previous release. I'm hoping to get this in now, all we're missing at the moment for this one are the spec tests which will help us keep this healthy in time and avoid breaking anything. If you could take a stab at those, that'd be really awesome 🙇

**Comment by truthbk** [comment]
@yrcjaya any chance you could give those spec tests a shot? `1.11.0` will be released soon and I would love to include this in it. Let me know! Thanks :)

**Comment by esg-gustavo** [comment]
@truthbk @yrcjaya Any idea of when this will be merged? Has someone from Datadog had a chance to write those spec tests?

**Comment by yrcjaya** [comment]
@truthbk Merged the conflicting commit.

**Pull request merged**
