### PR TITLE
Manage repo for ubuntu

### PR DESCRIPTION
**Pull request by supernovae**
- add wrapper to manage repo
- change from include to class to add parameter

### CODE REVIEW

**Comment by supernovae** [comment]
Right now the manage repo flag only works with rhel, we have a lot of ubuntu and use a private repo, so i just borrowed the same pattern from redhat and used it on ubuntu.

**Comment by truthbk** [comment]
@supernovae Thanks for implementing this! I was going to do so myself when I found the time (famous last words...).  There may be some conflicts with #242 ... Could you please rebase to the latest `master`? Thank you so much!

**Comment by supernovae** [comment]
I'll pull rebase with master tomorrow and update. Thx!

**Comment by supernovae** [comment]
Moving to:

https://github.com/DataDog/puppet-datadog-agent/pull/300

**Pull request closed without merging**
