### PR TITLE
Add ceph integration

### PR DESCRIPTION
**Pull request by stamak**

### CODE REVIEW

**Comment by truthbk** [comment]
Hi @stamak! Thanks a lot for this. I'm sorry it took me so long to acknowledge this and start reviewing. Can I ask you for a favor? Could you please rebase this to the latest master (there was an issue in the CI that has now been fixed). 

Ideally, we would also like to have some spec tests to keep some sort of track in the CI for the behavior of the manifest and avoid breaking things in the future, so if you could write something to that regard that would be great. If you don't have the time, please just let me know and I'll try to write those tests myself.

Thank you very much for your work! 👍

**Comment by stamak** [comment]
@truthbk done ;)

**Comment by truthbk** [comment]
Awesome stuff @stamak, I'll give this another pass later and almost certainly merge! Big 🏅  for the tests!

**Comment by truthbk** [comment]
We should make the actual integration configurable, so the `ceph` check parameters can be tweaked, but since this covers 99% of the cases I'll be merging this in.

**Pull request merged**
