### PR TITLE
Parameter expansion

### PR DESCRIPTION
**Pull request by obowersa**
Pull request to expand the current testing spec to cover paramaters in datadog.conf.erb in addition to expanding the parameters to cover (almost) all config options.

Not necessarily expecting this to get pulled but it's probably worth figuring out of this is a good approach to take.

### CODE REVIEW

**Comment by LeoCavaille** [comment]
Nice work! We've queued some work on the puppet module, and try to figure out a solution to the problem you raised. We'll review that by then.
Thanks again for contributing @obowersa

**Comment by ryandoherty** [comment]
Any info on when this will be merged? I've run in to a problem where I can't change the listen address, which is a PITA.

**Comment by truthbk** [comment]
@ryandoherty I'm going to try to squeeze this into 1.7.0, I'm running some tests to make sure everything looks good. It's been a long time coming, our apologies for that.

**Comment by truthbk** [comment]
Included in #176, thanks!

**Pull request closed without merging**
