### PR TITLE
[puppet] dogstatsd should be on by default.

### PR DESCRIPTION
**Pull request by truthbk**

### CODE REVIEW

**Comment by Ricky-Thomas** [comment]
Thanks again for looking at this @truthbk . This should resolve the issue here: https://github.com/DataDog/puppet-datadog-agent/issues/184

**Comment by bflad** [comment]
Ha yeah, this bit us too. Would love to have it turned back on by default, as well as for backwards compatibility in 1.x.

**Comment by truthbk** [comment]
Tested manually - successfully.

**Comment by hkaj** [comment]
do we still need lines 28-30 in `.travis.yml`?

**Comment by truthbk** [comment]
I removed the Travis changes. Those should go into its own PR. Unfortuntely due to the issue with the `listen` gem and its requirements of ruby >2.2.4, the CI tests will still error. These changes I've also tested manually successfully.

**Comment by hkaj** [comment]
👍 - LGTM

**Pull request merged**
