### PR TITLE
[postfix] Add an integration to handle Postfix instances

### PR DESCRIPTION
**Pull request by npaufler**

### CODE REVIEW

**Comment by truthbk** [comment]
Hi @npaufler! Thanks for pinging me via slack. I'll be reviewing this today. Right off the bat it's looking pretty solid! I did notice we're missing some spec tests for this one as well. If you could add a couple, that would be golden! It shouldn't take long.

**Comment by truthbk** [comment]
As mentioned in your other PR @npaufler, we'll be releasing `1.11.0` soon, so if you could find the time to write them so we can merge this and release I'd really appreciate that! 🙇

**Comment by npaufler** [comment]
Sure thing - working on it right now - running into some issues with it but hoping to have it ready before the weekend.

**Comment by npaufler** [comment]
@truthbk Okay - this one is done as well.

**Pull request merged**
