### PR TITLE
[memcache] Add multi-instance support for memcache

### PR DESCRIPTION
**Pull request by npaufler**
Added multiple-instance support for memcache (similar to the implementation for the MySQL integration).

### CODE REVIEW

**Comment by truthbk** [comment]
Hi @npaufler could you please rebase to the latest `master`? After bringing in the latest changes to your forked repo: 

```
git checkout master
git pull
git checkout 20170331-memcache-multi-instance
git rebase master
git push -f origin 20170331-memcache-multi-instance
```

Thank you! I'll take a look at this ASAP.

**Comment by npaufler** [comment]
Sorry for the delay, @truthbk - was traveling late last week. I've rebased against the most recent master and pushed it up.

Thanks

**Comment by truthbk** [comment]
@npaufler as we discussed on slack, any chance you'll be able to write those juicy tests :) Let me know if you need anything!

**Comment by npaufler** [comment]
It was on my to do list for this week but it unfortunately some other things came up. Hoping to take a look this weekend or early next week :)

Thanks for checking in

**Comment by truthbk** [comment]
@npaufler we'll be releasing `1.11.0` sooner rather than later, so if you could give those spec tests a shot, so we can merge and release this, that would be fantastic. Let me know if you have any questions.

**Comment by npaufler** [comment]
@truthbk Done - specs are now in place for the mcache improvements.

**Pull request merged**
