### PR TITLE
Support use_pscopg2 flag for postgres integrations

### PR DESCRIPTION
**Pull request by sethcleveland**

### CODE REVIEW

**Comment by sethcleveland** [comment]
Closing the loop with this PR -- https://github.com/DataDog/dd-agent/pull/2782.

**Comment by sethcleveland** [comment]
@truthbk is there anything I can do to get this merged in?

**Comment by truthbk** [comment]
@sethcleveland apologies, I was out for a few days. Changes are straight-forward, but I see some tests are failing. You might want to rebase to the latest `master` and see if that fixes anything? If you don't have the time to fix the broken tests, let me know.

**Comment by sethcleveland** [comment]
@truthbk looks like the rebase worked. Thanks!

**Comment by truthbk** [comment]
thanks @sethcleveland merging!

**Pull request merged**
