### PR TITLE
Add postgres custom metrics

### PR DESCRIPTION
**Pull request by ipolishchuk**
This pull request is a replacement for https://github.com/DataDog/puppet-datadog-agent/pull/69
It fixes a typo in the londiste3 last_seen metric definition and adds another example of a custom metrics tx_duration_92. There are two metrics here postgresql.max_tx_duration - largest transacrion duration, and postgresql.max_query_duration -- largest query duration for active sessions. The tx_duration_92 metrics are for postgres v9.2+
An extra value of  tx_duration_92, it provides a working format sample for a metric without descriptor.

### CODE REVIEW

**Comment by talwai** [comment]
Upstream dd-agent PR: https://github.com/DataDog/dd-agent/pull/1395

**Comment by LeoCavaille** [comment]
We probably want to merge this, but re-work it a bit to allow more liberty in defining the custom metrics dictionary rather than enabling pre-written metrics like `londiste3_last_seen` or `tx_duration_92`. People should be able to define that in the class and fill the template not the other way around IMO.
Putting it in standby for now and it would probably helped by a refactoring of the classes.
Feel free to use it on top of the current release if needed.

**Comment by sethcleveland** [comment]
Custom metric support provided here -- https://github.com/DataDog/puppet-datadog-agent/pull/224.

**Comment by truthbk** [comment]
Superceded by #224 - closing. Thanks regardless @ipolishchuk 🙇

**Pull request closed without merging**
