### PR TITLE
Added USM

### PR DESCRIPTION
**Pull request by guyarb**
### What does this PR do?

Adds USM

### Motivation

USM is GA

### CODE REVIEW

**Review by apigirl — APPROVED** [review]
docs look good

**Review by bkabrda — APPROVED** [review]

**Comment by guyarb** [comment]
@bkabrda is the kitchen test supposed to fail?

**Comment by bkabrda** [comment]
@guyarb it's not. I think this is the problem that we fixed on the `main` branch already, could you please rebase on latest `main`?

**Comment by guyarb** [comment]
@bkabrda I rebased the branch but i dont have write access to the repo
can you merge it?

**Pull request merged**
