### PR TITLE
Feature: Cassandra integration

### PR DESCRIPTION
**Pull request by aaron-miller**
Added the ability to manage Cassandra integration configuration file for agents.

### CODE REVIEW

**Comment by aaron-miller** [comment]
It appears that the build is failing not due to the changes, but due to Bundler errors before any tests actually run.

**Comment by truthbk** [comment]
@aaron-miller thanks for this one! You are indeed correct, the issue with travis was caused to a hard dependency on ruby >2.2.4 or something on the newest version of the `listen` gem (which is a requirement). That should now be fixed on `master` so if you could rebase to that, it would be great! That should allow travis to do its thing.

**Comment by aaron-miller** [comment]
Things are looking better now! Thanks @truthbk!

**Comment by truthbk** [comment]
@aaron-miller again, amazing work. Thanks a lot for keeping the catalog of supported integrations growing! Can't thank you enough for the spec tests! 😍

**Pull request merged**
