### PR TITLE
Improve apt repository

### PR DESCRIPTION
**Pull request by rhoml**
- Improve repository management
- Fix some tests

### CODE REVIEW

**Comment by LeoCavaille** [comment]
Looks awesome, will get someone to review it shortly! Thanks!

**Comment by rhoml** [comment]
@LeoCavaille great :+1:

**Comment by rhoml** [comment]
Any news on this? should I rebase?

**Comment by rhoml** [comment]
Any news on this change?

**Comment by truthbk** [comment]
@rhoml sorry we've taken so long to check this out. I will review this very shortly (this time for real ;) and see if there's anything else we need to do before merging. Thank you for your contribution and patience!

**Comment by rhoml** [comment]
Guess this is not going to get merged any time soon.

**Comment by truthbk** [comment]
@rhoml the problem with this is that I believe the `apt` module is not supported in the older puppets that the current module does support (puppet forge docs/version reporting aren't great so I could be wrong though) - this has been an issue with a few PRs, where we've had to hold them until we had a clear date for a `2.0` release of the check where we could drop the old-school dependencies to support puppets <4, and to allow us to include updated modules. 😞

**Comment by rhoml** [comment]
Dropping this PR as this will never be merged.

**Pull request closed without merging**
