### PR TITLE
Added cacti integration

### PR DESCRIPTION
**Pull request by sambanks**
Basic integration for cacti

### CODE REVIEW

**Comment by truthbk** [comment]
@sambanks thank you for this. I will fix the CI in the next couple of days and ask you to rebase to the latest master before merging. Any chance you could add some spec tests? We're trying to keep as much of the code as we can spec tested. I'll give you a heads-up once the issue with the CI is addressed.

**Comment by sambanks** [comment]
Sure thing, will do. Let me know when it's up and running again.

Cheers
Sam

**Comment by sambanks** [comment]
Took me a couple of goes, as it was my first time doing spec tests, but looks good now.

**Comment by truthbk** [comment]
Nice @sambanks! Let's merge this guy in! 🙇

**Pull request merged**
