### PR TITLE
Config variable to enable the trace agent

### PR DESCRIPTION
**Pull request by DDRBoxman**

### CODE REVIEW

**Comment by truthbk** [comment]
Thanks a lot for this. Definitely something we wanted in the next release (coming up soon). @DDRBoxman could you please rebase to the latest master to make sure the CI is green (that fixed was merged in earlier). Also, if you have the time (otherwise don't worry about it), could you please add a small spec test for this change? Thanks so much 🙇

**Comment by DDRBoxman** [comment]
Should be good to go now 😀

**Comment by Tonkonozhenko** [comment]
Can you add passing `env` to `trace.config` sections please? Some docs are here: [link](https://app.datadoghq.com/apm/docs/tutorials/environments).

**Comment by truthbk** [comment]
@DDRBoxman this is great and ready to go. But @Tonkonozhenko has a good point, and it'd be the only missing piece to this PR. Would you have the time to implement? Don't worry if you're swamped on other stuff.

**Comment by truthbk** [comment]
I am assuming @DDRBoxman is swamped, so I'll merge this and open a PR to implement the env stuff. Thanks again for adding this.

**Pull request merged**
