### PR TITLE
Using apt module for keys

### PR DESCRIPTION
**Pull request by craigwatson**

### CODE REVIEW

**Comment by craigwatson** [comment]
@truthbk Any chance of getting this (and my other PR) merged?

**Comment by truthbk** [comment]
@craigwatson this would be preferable indeed, we'll have to ensure this doesn't break on older puppets. Unfortunately we're still trying to maintain backward compatibility for older puppets. Working on a new release now, so I'll double-check this.

Thank you for the PR! 🙇

**Comment by truthbk** [comment]
@craigwatson indeed this would break on older puppets as we can see here: https://forge.puppet.com/puppetlabs/apt

I'm not going to close the PR for now as I want to to keep this in my radar when the next major release for the agent happens.

**Comment by truthbk** [comment]
@craigwatson I mean we have people still on puppet 2.7 using this module. Puppet 2.0 will be a clean slate to that regard (dropping support for all EOL'd puppets). You can see on-going changes here: https://github.com/DataDog/puppet-datadog-agent/pull/387

I'll probably close this PR soon given these are some of the changes we brought into that PR.

**Comment by truthbk** [comment]
#387 has been merged with similar changes. Thank you very much @craigwatson for raising this, very much appreciated.

**Pull request closed without merging**
