### PR TITLE
Allow configuration of more things.

### PR DESCRIPTION
**Pull request by gphat**
# What's this PR do?

Allows the configuration of: 
* the DogstatsD port
* the forwarder's SSL validation.
* statsd forwarding host and port

# Motivation

Some customers — such as me! — run existing StatsD and proxies. Being able to configure these things without having to make vendored changed would be great!

### CODE REVIEW

**Comment by remh** [comment]
Thanks a lot @gphat ! We'll review this shortly.

**Comment by gphat** [comment]
Hey @remh and @talwai!

Sorry to give you a moving target when with the appearance of the `5.5.0` this morning — which my boxes won't install, is it signed? — I realized that pinning the version is another thing we'd want. Otherwise we might have an unplanned, untested upgrade!

**Comment by gphat** [comment]
I had to remove the test for `latest` in RedHat, which feels clunky. The Ubuntu version didn't test this at all. Looks like the form in which that test is run doesn't get the variable set, so it will of course be nil.

Not sure how to test approach that. I'm happy to pluck that change if it's contentious or needs more work.

**Comment by talwai** [comment]
@gphat Thanks for the updates, we'll dig into them very soon. In the mean time, could you tell us the exact issue you were having with installing `5.5.0`. Details about your OS would also be greatly appreciated

**Comment by gphat** [comment]
My OS:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

When `5.5.0` showed up yesterday I started getting errors:
```
/usr/bin/apt-get -V -y -o DPkg::Options::=--force-confold install datadog-agent
...
WARNING: The following packages cannot be authenticated!
  datadog-agent
E: There are problems and -y was used without --force-yes
```

I verified the key was installed:
```
/usr/bin/apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C7A7DA52
gpg: requesting key C7A7DA52 from hkp server keyserver.ubuntu.com
gpg: key C7A7DA52: "Datadog Packages <package@datadoghq.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

But it still doesn't want to work. I dunno anything about package signing, so I'm not much help. :(

**Comment by gphat** [comment]
Ping! (Not urgent, just perusing my backlog!)

Happy to break this PR up a bit and also to move the package bits to a support thing if desired.

**Comment by gphat** [comment]
Ignore the key problems, that's on my end. Deleting the comments for clarify.

**Comment by gphat** [comment]
friendly ping!

**Comment by gphat** [comment]
Just added override `ca_certs` as per discussion in [dd-agent#1964](https://github.com/DataDog/dd-agent/issues/1964). Another friendly ping on this.

**Comment by talwai** [comment]
Sorry for the delay @gphat ! Looking into it this week

**Comment by gphat** [comment]
No worries! I've been using a vendored version so I'm not blocked. Just don't want to diverge too much!

**Comment by talwai** [comment]
Hey @gphat we plucked some of your changes into #136 which was just merged

**Comment by gphat** [comment]
Cool, thanks! Looks like the package version was the only thing left out. Why's that?

**Comment by talwai** [comment]
We left it out in the near term because it was causing CI to fail, and it surfaced some other improvements we could make to the way we mock out variables in spec tests. It's a change we really should make though, and we'll look to incorporate your commit as soon as the work on our end catches up

**Comment by gphat** [comment]
Sounds great! This means I'm slightly less diverged from your version, which is always a win. Thanks @talwai!

**Comment by truthbk** [comment]
@gphat closing this guy, as @talwai mentioned most of your changes were plucked into: https://github.com/DataDog/puppet-datadog-agent/pull/136

Thanks again!

**Pull request closed without merging**
