### PR TITLE
Rhoml/add patterns dogstreams

### PR DESCRIPTION
**Pull request by rhoml**
Add dogstreams capability

TODO: custom parser provisioning

### CODE REVIEW

**Comment by talwai** [comment]
Hi @rhoml can you elaborate on the `patterns.d` directory and what the intended use is? It's not immediately clear in the diff

**Comment by rhoml** [comment]
@talwai Added it on the resource would this be enough?

**Comment by LeoCavaille** [comment]
@rhoml I think @talwai was trying to question about the `patterns.d` that you are creating in the module. It is not something that exists and is used in the dd-agent code. Is that a custom directory you are using for your dogstreams?

**Comment by LeoCavaille** [comment]
Also this was already merged. https://github.com/DataDog/puppet-datadog-agent/commit/14662c2505ff7dcafe64add09ef8b86bded94a4a
So closing this in the meantime, feel free to reopen if needed.

**Pull request closed without merging**
