### PR TITLE
Add ganglia configuration

### PR DESCRIPTION
**Pull request by phibesse**
Just add the possibility to setup ganglia as a metric source.

### CODE REVIEW

**Comment by talwai** [comment]
Hi @phibesse @dominics . Our Ganglia integration is actually [deprecated](https://github.com/DataDog/dd-agent/pull/1621), and slated for removal in a future version of the Datadog Agent. Could you say a bit more about how you're using the integration, and how heavily you're relying on it?

**Comment by phibesse** [comment]
Hi @talwai , We rely heavily on it, when do you plan to remove it?
Do you have any workaround?

**Comment by talwai** [comment]
@phibesse we are tentatively planning on weeding it out by the `6.0` release. Currently [this issue](https://github.com/DataDog/dd-agent/issues/1632) describes what we see as a good workaround for existing Ganglia users in the event that the integration is removed from the agent core. Help on it is welcome!

**Comment by talwai** [comment]
Hi @phibesse , we rebased your changeset and merged it in PR #124 . Thanks again for contributing!

**Pull request closed without merging**
