### PR TITLE
Remove include call outside class

### LINKED ISSUE #593: Server Error: This Function Call is unacceptable as a top level construct in this location
Line one in manifests/system_probe.pp (`include datadog_agent::params`) is causing puppet 6 to fail with the above message. As it seems like an unnecessary line (the other PPs don't have it), it should probably be removed. Tests with removing it work fine for us, and we cannot use DD's puppet module with the line in place.

### PR DESCRIPTION
**Pull request by albertvaka**
Fixes #593

### CODE REVIEW

**Comment by albertvaka** [comment]
@asenci

**Comment by albertvaka** [comment]
Done in #596

**Comment by asenci** [comment]
> @asenci I guess this can be removed.

Sorry, I missed the notification for this mention 🙈. End up hitting the same problem after upgrading to 6.7 a couple of days ago.

**Comment by albertvaka** [comment]
No worries :)

I will release a new version with the fix likely tomorrow.

**Pull request closed without merging**
