### PR TITLE
Adding ability to manage disk.yaml

### PR DESCRIPTION
**Pull request by babyhuey**
Added disk.pp and disk.yaml.erb.

This allows the use of puppet to manage the disk.yaml config file through Puppet.

### CODE REVIEW

**Comment by velebak** [comment]
+1

**Comment by truthbk** [comment]
@babyhuey thanks for your PR! I'll review and test this soon. 😄

**Comment by truthbk** [comment]
@babyhuey the template `.erb` is basically spitting a pre-configured file that isn't really configurable at all... That'd limit the usability of this integration with puppet pretty severely for other users. Do you think you can find the time to work on that? Let me know if it's not the case! Thanks a lot!

**Comment by truthbk** [comment]
An alternative PR (https://github.com/DataDog/puppet-datadog-agent/pull/263) was merged instead. Thank you regardless @babyhuey!

**Pull request closed without merging**
