### PR TITLE
mesos, docker, consul, repo, disk

### PR DESCRIPTION
**Pull request by flyinprogrammer**
fix mesos with new checks
add dd user to docker group
update to use docker_daemon
add consul
allow repo to be optionally managed
use_mount is now managed in disk.yaml

### CODE REVIEW

**Comment by flyinprogrammer** [comment]
this is https://github.com/DataDog/puppet-datadog-agent/pull/153 only updated with master changes because we updated to puppet 4... it'd be cool if we merged this.. or didn't and i'll maintain a fork, just let me know.

**Comment by irabinovitch** [comment]
@truthbk @remh Making sure you saw this one.

**Comment by truthbk** [comment]
@irabinovitch taking note, will include this in the release - I'm back working on it.

**Comment by truthbk** [comment]
Included in #176, thanks!

**Pull request closed without merging**
