### PR TITLE
Removing include datadog_agent, adding Class require. Cleaning up lin…

### PR DESCRIPTION
**Pull request by shawn-sterling**
Hello,

This removes the include datadog_agent from the integrations, because if you are calling datadog_agent with parameters, and an integration gets included first, it will include the datadog_agent without parameters; and when you try to call it with params you will get duplicate declaration errors.

This is happening because we are using roles and profiles, and in our profiles we are doing stuff like

```
class profile::apache {
    include ::datadog_agent::integrations::apache
}
```

which inside the integration does a 

```
include datadog_agent
```

which might get called before we call our parameterized datadog_agent:

```
class profile::monitoring::datadog {
    class { '::datadog_agent':
        params => foo
    }
}
```

and then cause a duplicate definition error:

```
Error: Duplicate declaration: Class[Datadog_agent] is already declared; cannot redeclare at 
```

This merge will get rid of that problem and still keep the the datadog_agent as a requirement for the integrations.

### CODE REVIEW

**Comment by truthbk** [comment]
Thanks for this @shawn-sterling, very interesting. I'll take a good look at this one, because we don't want to break anything for existing user's manifests (not saying this will, we've just got to be extra careful). As a starting point could you please rebase to the latest `master`  so we get CI running properly again (just fixed travis yesterday).

**Comment by shawn-sterling** [comment]
Somehow I missed this response, I'll rebase shortly.

**Comment by shawn-sterling** [comment]
Okay, that was confusing, but found this: https://github.com/rodjek/puppet-lint/issues/509 in the process. ;)

I understand about not wanting to break anything for existing user's manifests, and this shouldn't break anyone unless they they were doing something like including an integration class only and not including the datadog_agent class; in which case it would fail. I'm not sure there is a good way around that one; but as far as I'm concerned that's something you shouldn't be doing. :)

Let me know if you would like any further revisions.

**Comment by truthbk** [comment]
@shawn-sterling ugh.... I was preparing a new release and merged a few PR's and that seems to have caused a few conflicts. Don't want to abuse your patience and help, would you be able to fix those?

**Comment by shawn-sterling** [comment]
Yup, will have it fixed shortly.

**Comment by truthbk** [comment]
I was working on a rebase of your work (to solve the conflicts) and it occurred to me that perhaps we could get around the issue you had found by `require ::datadog-agent` as opposed to `include ::datadog-agent` - as we do here https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/integrations/cassandra.pp#L32

And that would possibly allow us to change less code and keep the spec tests and linting intact. I'm  going to try to reproduce what you originally reported and see if that cuts it. If we could change less code, it would be preferable.

**Comment by vorgusa** [comment]
Is this still being planned, I constantly get Duplicate declaration errors

**Comment by shawn-sterling** [comment]
I fixed this a couple times in 2016, they didn't end up getting merged for whatever reason (people get busy, I understand). 

I no longer work somewhere that uses puppet, so I haven't touched puppet in a couple years. As I look thru the code I think that these changes are likely still a good idea if they haven't been done elsewhere.

@vorgusa feel free to take this and fix yourself in your own PR (or don't, whatever makes you happy).

@truthbk feel free to close this PR.

Have a good day!

**Pull request closed without merging**
