### PR TITLE
Support cassandra integration tags

### PR DESCRIPTION
**Pull request by sethcleveland**
- Change tags to match jmx fetch's data dog -- array to hash

### CODE REVIEW

**Comment by sethcleveland** [comment]
@truthbk JMX fetch expects a hash.  here's the corresponding JMX code that fails when tags is an array --https://github.com/DataDog/jmxfetch/blob/e69217c32c51afed312aa3a54e7125912c429cab/src/main/java/org/datadog/jmxfetch/Instance.java#L71.

This can be address either in puppet or the jmxfetch app. This code reflects changing puppet to match JMX fetch. JMXFetch can also be changed to be an array.

**Comment by sethcleveland** [comment]
https://github.com/DataDog/puppet-datadog-agent/issues/255

**Comment by truthbk** [comment]
This looks good @sethcleveland! Thanks a bunch for the test. We'll be releasing an updated module soon. 👍

**Comment by sethcleveland** [comment]
Cool, looking forward to that release! 👍

**Pull request merged**
