### PR TITLE
Configure redis slowlen_max_len

### LINKED ISSUE #115: Redis slowlog_max_len not configurable in module but raises warning in collector
For redis servers configured with a non-default slowlog max len, collector issues a warning. Also, users who have configured their redis instance with a higher length probably want access to that data. Error message from `sudo service datadog-agent info`:

[WARNING]:Redis slowlog-max-len is higher than 128. Defaulting to 128.If you need a higher value, please set slowlog-max-len in your check config

Puppet agent template doesn't have this as an option, nor does the manifest accept it as a setting.

### PR DESCRIPTION
**Pull request by StephenWeber**
Fixes #115

### CODE REVIEW

**Comment by StephenWeber** [comment]
Update to make setting slowlen_max_len less error prone and more consistant with other parameters.

**Comment by remh** [comment]
Thanks for this @StephenWeber we'll review this shortly.

**Comment by talwai** [comment]
HI @StephenWeber , thanks for contributing and sorry for the delay in feedback! There's an inconsistency between your template variable and the one declared in the manifest (`slowlog_len  v/s slowlog_max`). Also we probably want to keep the variable name as close to the one [specified in the dd-agent yaml file as possible](https://github.com/DataDog/dd-agent/blob/master/conf.d/redisdb.yaml.example#L41) so `$slowlog_max_len` seems most reasonable. Would you mind fixing that so we can merge?

**Comment by StephenWeber** [comment]
No worries! I'll get another patch in for the name change. There was also a round of testing that gave me trouble with validating the type, which led to that last change - do you have any feedback on validating input values? Or is the current string-based scheme sufficient?

**Comment by talwai** [comment]
@StephenWeber Yea unfortunately we have seen some quirks with validating integers in Puppet and have ended up not trusting the native function too much. See [here](https://ask.puppetlabs.com/question/3298/how-do-i-use-validate_re-to-check-integers/) for more elaboration. I think your string-based scheme is sufficient for now - we are looking at using `puppetlabs-stdlib` for the next major release which will give us some nicer validation wrappers.

**Comment by talwai** [comment]
Thanks for contributing @StephenWeber , I rebased your changes onto master and merged them as part of #132

**Pull request closed without merging**
