### PR TITLE
Change default port values to strings, as expected by datadog.conf.erb

### PR DESCRIPTION
**Pull request by Dvanderspuij**
If the port variables are not defined, puppet will fail on parsing the template.

__Error when parsing template__ 
Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template datadog_agent/datadog.conf.erb:
==> nodejs-es:   Filepath: /tmp/vagrant-puppet/modules-71d71bfb0a46455123a5017c4c54e211/datadog_agent/templates/datadog.conf.erb
==> nodejs-es:   Line: 137
==> nodejs-es:   Detail: undefined method `empty?' for 8125:Fixnum

### CODE REVIEW

**Comment by joelnn** [comment]
+1, I ran into this with 1.5.0

**Comment by wazoo** [comment]
I also ran into this in 1.5.0, I was able to get around it by just overriding the defaults in my wrapper class to be strings (still using default values) if anyone else is looking for a fix until this is merged.

**Comment by truthbk** [comment]
Thanks for this @Dvanderspuij , we identified the root cause and addressed it with https://github.com/DataDog/puppet-datadog-agent/commit/62446593ebaa3bf3061d8407c440c0cbd1131909 in PR #161 

This should be sorted in our next release! :)

**Comment by Dvanderspuij** [comment]
:+1: Nice.

**Pull request closed without merging**
