### PR TITLE
fix consul to be the new consul_check

### PR DESCRIPTION
**Pull request by flyinprogrammer**
newer versions of dd-agent require this to be consul_check.yaml

### CODE REVIEW

**Comment by flyinprogrammer** [comment]
I believe this changed in 5.8.2 sometime around this commit: https://github.com/DataDog/dd-agent/commit/9f2b4f95b47798a0e90e9448f405094197073c6f

**Comment by truthbk** [comment]
As with all your other contributions thanks @flyinprogrammer! We might want to try to parametrize the filename somehow so we can keep backward compatibility somehow as I know there's still a considerable userbase still on `5.7.x`. Also, could you please rebase to the latest master so we can get CI rolling and 💚 again?

**Comment by flyinprogrammer** [comment]
@truthbk both of those things make sense! my week this week is a little crazy - I'll try to get this done by Monday.

**Comment by flyinprogrammer** [comment]
i haven't forgotten about this, just been busy.

**Comment by truthbk** [comment]
@flyinprogrammer thanks for the update! We're now all green. How do you feel about making the filename into a parameter? We should try to keep backward compatibility as much as possible.

**Comment by flyinprogrammer** [comment]
@truthbk i feel good about it 👍 let me see if i can get this done right now.

**Comment by truthbk** [comment]
@flyinprogrammer you the man! 👍

**Comment by flyinprogrammer** [comment]
`1:5.8` and `5.8` makes me real sad, but I don't know what else to do.

**Comment by truthbk** [comment]
@flyinprogrammer thank so very much! We can maybe check if $datadog_agent::agent_version.index(':') == 1 and then just strip out the `1:` and that _should_ allow the version comparisons to always make sense. What do you think?

**Comment by flyinprogrammer** [comment]
@truthbk that makes sense - i'm headed to Australia for 2 weeks tonight -- I'll try and find some time to get this fixed up (Maybe on the flight if there's intertubes.)

**Comment by truthbk** [comment]
@flyinprogrammer enjoy your trip! Australia, definitely got that in my bucket list.

**Comment by flyinprogrammer** [comment]
o.m.g. I suck. if my flight has wifi, I will work on getting this done, otherwise it might be another week. I'm so sorry @truthbk this must be so frustrating. I wanted to actually write Beaker tests that prove this stuff works.

**Comment by truthbk** [comment]
@flyinprogrammer no worries at all, all the work and time you put in is always appreciated. So no frustration at all, just thankful for the community's contributions.

**Comment by flyinprogrammer** [comment]
alright - with some luck maybe i can get something done for this before our little re:invent happy hour

**Comment by flyinprogrammer** [comment]
so do not merge this, there is a rumor that the config file name changed again in 5.9 -- i'm looking for the commit now.

**Comment by flyinprogrammer** [comment]
wow so this PR was started because of an internal change we made to our internal datadog agent related to https://github.com/DataDog/dd-agent/issues/2123 

Meaning, we had renamed `consul.py` to `consul_check.py` so that there would not be an import namespace problem.

Meaning this PR does nothing but break the open source public facing project. **Those who stumble upon this PR should literally ignore everything in this.**

I am super sorry, this is super embarrassing. I will however, go create a new PR with some tests for the consul integration!

**Pull request closed without merging**
