### PR TITLE
Add supervisord integration config files

### PR DESCRIPTION
**Pull request by cristianjuve**

### CODE REVIEW

**Comment by marcgascon** [comment]
Hello @truthbk is there any problem with the PR? we need it to continue working with DataDog.

**Comment by truthbk** [comment]
@cristianjuve @marcgascon there's nothing wrong with the PR. Actually it looks quite good, but it's missing the spec tests. It would be great if you could add a few. Thank you so much for the contribution.

**Comment by cristianjuve** [comment]
Hi @truthbk, I've created spec tests :) check the spec file and if is all OK, please merge this PR :)

Thk!

**Comment by truthbk** [comment]
@cristianjuve Awesome, very nice! Thank you so much! Sorry to make you do that, we're just trying to keep as much of the manifests tested as possible. 

Merging!

**Pull request merged**
